import Image from 'next/image';

export default function Home() {
	return (
		<>
			<div>
				<img
					src="/images/mega-menu-with-catalog-nextjs-shadcn-v2-900x525.png"
					alt="IMAGE"
					width={1000}
					height={800}
				/>
			</div>
			<div>
				<img
					src="/images/mega-menu-nextjs-shadcn-v2-900x525.png"
					alt="IMAGE"
					width={1000}
					height={800}
				/>
			</div>
			<div>
				<img
					src="/images/mega-menu-nextjs-shadcn-v3-900x525.png"
					alt="IMAGE"
					width={1000}
					height={800}
				/>
			</div>
			<div>
				<img
					src="/images/features-530x685.png"
					alt="IMAGE"
					width={1000}
					height={800}
				/>
			</div>
			<div>
				<img
					src="/images/mega-menu-nextjs-shadcn-v4-900x500.png"
					alt="IMAGE"
					width={1000}
					height={800}
				/>
			</div>
			<div>
				<img
					src="/images/admin-panel-900x418.png"
					alt="IMAGE"
					width={1000}
					height={800}
				/>
			</div>
			<div>
				<img
					src="/images/mobile-dark.png"
					alt="IMAGE"
					width={1000}
					height={800}
				/>
			</div>
			<div>
				<img
					src="/images/mobile-light.png"
					alt="IMAGE"
					width={1000}
					height={800}
				/>
			</div>
			<div>
				<img
					src="/images/mobile-2-900x500.png"
					alt="IMAGE"
					width={1000}
					height={800}
				/>
			</div>
			<div>
				<img
					src="/images/mobile-3-900x500.png"
					alt="IMAGE"
					width={1000}
					height={800}
				/>
			</div>
			<div>
				<img
					src="/images/portfolio-menu-min-900x575.png"
					alt="IMAGE"
					width={1000}
					height={800}
				/>
			</div>
			<div>
				<img
					src="/images/full-screen-menu-900x480.png"
					alt="IMAGE"
					width={1000}
					height={800}
				/>
			</div>
		</>
	);
}
